"""empty message

Revision ID: caa338621d40
Revises: 
Create Date: 2022-09-27 22:29:04.294158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa338621d40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_category',
    sa.Column('loan_categoryID', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_shares', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('repayment_duration', sa.Integer(), nullable=False),
    sa.Column('qualification_duration', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('loan_categoryID'),
    sa.UniqueConstraint('loan_categoryID')
    )
    op.create_table('staff',
    sa.Column('staffID', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('national_id', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('staffID'),
    sa.UniqueConstraint('staffID')
    )
    op.create_table('transaction',
    sa.Column('transactionID', sa.String(length=8), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('transaction_code', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transactionID'),
    sa.UniqueConstraint('transactionID')
    )
    op.create_table('member',
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('memberNo', sa.String(length=5), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('national_id', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('id_front', sa.String(length=255), nullable=False),
    sa.Column('id_back', sa.String(length=255), nullable=False),
    sa.Column('kra_pin', sa.String(length=255), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('email_confirmed', sa.String(length=40), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['staffID'], ['staff.staffID'], ),
    sa.PrimaryKeyConstraint('memberID'),
    sa.UniqueConstraint('memberID'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('OTP',
    sa.Column('otpID', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('password', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memberID'], ['member.memberID'], ),
    sa.PrimaryKeyConstraint('otpID'),
    sa.UniqueConstraint('otpID')
    )
    op.create_table('deposit',
    sa.Column('depositID', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=False),
    sa.Column('deposit_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memberID'], ['member.memberID'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.transactionID'], ),
    sa.PrimaryKeyConstraint('depositID'),
    sa.UniqueConstraint('depositID')
    )
    op.create_table('loan',
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loan_categoryID', sa.String(length=8), nullable=False),
    sa.Column('staffID', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['loan_categoryID'], ['loan_category.loan_categoryID'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.memberID'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.staffID'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.transactionID'], ),
    sa.PrimaryKeyConstraint('loanID'),
    sa.UniqueConstraint('loanID')
    )
    op.create_table('collateral',
    sa.Column('collateralID', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['loanID'], ['loan.loanID'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.memberID'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.staffID'], ),
    sa.PrimaryKeyConstraint('collateralID'),
    sa.UniqueConstraint('collateralID')
    )
    op.create_table('guarantor',
    sa.Column('guarantorID', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['loanID'], ['loan.loanID'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.memberID'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.staffID'], ),
    sa.PrimaryKeyConstraint('guarantorID'),
    sa.UniqueConstraint('guarantorID')
    )
    op.create_table('repayment',
    sa.Column('repaymentID', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loanID'], ['loan.loanID'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.memberID'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.transactionID'], ),
    sa.PrimaryKeyConstraint('repaymentID'),
    sa.UniqueConstraint('repaymentID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment')
    op.drop_table('guarantor')
    op.drop_table('collateral')
    op.drop_table('loan')
    op.drop_table('deposit')
    op.drop_table('OTP')
    op.drop_table('member')
    op.drop_table('transaction')
    op.drop_table('staff')
    op.drop_table('loan_category')
    # ### end Alembic commands ###
