"""empty message

Revision ID: 00e7c5ad41e9
Revises: 331463ae3772
Create Date: 2022-10-05 18:58:33.838106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e7c5ad41e9'
down_revision = '331463ae3772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'password')
    # ### end Alembic commands ###
