"""empty message

Revision ID: 331463ae3772
Revises: d0637c83a698
Create Date: 2022-10-05 10:20:36.957066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331463ae3772'
down_revision = 'd0637c83a698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('reason', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'reason')
    # ### end Alembic commands ###
