"""empty message

Revision ID: d0637c83a698
Revises: 
Create Date: 2022-10-04 09:51:48.263913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0637c83a698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.Column('deposit_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment')
    op.drop_table('guarantor')
    op.drop_table('collateral')
    op.drop_table('loan')
    op.drop_table('deposit')
    op.drop_table('OTP')
    op.drop_table('member')
    op.drop_table('transaction')
    op.drop_table('staff')
    op.drop_table('loan_category')
    # ### end Alembic commands ###
