"""empty message

Revision ID: d0637c83a698
Revises: 
Create Date: 2022-10-04 09:51:48.263913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0637c83a698'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loan_categoryID', sa.String(length=8), nullable=False),
    sa.Column('staffID', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('profile_status', sa.String(length=40), nullable=True),
    sa.Column('guarantor_status', sa.String(length=40), nullable=True),
    sa.Column('collateral_status', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['loan_categoryID'], ['loan_category.id'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment')
    op.drop_table('guarantor')
    op.drop_table('collateral')
    op.drop_table('loan')
    op.drop_table('deposit')
    op.drop_table('OTP')
    op.drop_table('member')
    op.drop_table('transaction')
    op.drop_table('staff')
    op.drop_table('loan_category')
    # ### end Alembic commands ###
