"""empty message

Revision ID: dd40f7dd65f5
Revises: d0637c83a698
Create Date: 2022-10-06 20:13:08.808260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd40f7dd65f5'
down_revision = 'd0637c83a698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('CheckoutRequestID', sa.String(length=30), nullable=True))
    op.add_column('repayment', sa.Column('CheckoutRequestID', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repayment', 'CheckoutRequestID')
    op.drop_column('deposit', 'CheckoutRequestID')
    # ### end Alembic commands ###
