"""empty message

Revision ID: f8d0c8ef2352
Revises: 
Create Date: 2022-10-30 22:45:23.319855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d0c8ef2352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_category',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_shares', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('repayment_duration', sa.Integer(), nullable=False),
    sa.Column('qualification_duration', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('national_id', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('transactionNo', sa.String(length=9), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('transaction_code', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('memberNo', sa.String(length=7), nullable=True),
    sa.Column('first_name', sa.String(length=40), nullable=True),
    sa.Column('last_name', sa.String(length=40), nullable=True),
    sa.Column('national_id', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('id_front', sa.String(length=255), nullable=True),
    sa.Column('id_back', sa.String(length=255), nullable=True),
    sa.Column('kra_pin', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('number_of_dependants', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('town', sa.String(length=50), nullable=True),
    sa.Column('estate', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('house_number', sa.String(length=50), nullable=True),
    sa.Column('house_ownership', sa.String(length=50), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('employer_name', sa.String(length=50), nullable=True),
    sa.Column('employer_address', sa.String(length=50), nullable=True),
    sa.Column('employer_phone', sa.String(length=50), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('years_of_operation', sa.Integer(), nullable=True),
    sa.Column('business_income', sa.Integer(), nullable=True),
    sa.Column('employment_terms', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('deposit',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.Column('CheckoutRequestID', sa.String(length=30), nullable=True),
    sa.Column('deposit_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('loan',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('loanNo', sa.String(length=7), nullable=True),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loan_categoryID', sa.String(length=8), nullable=False),
    sa.Column('staffID', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('profile_status', sa.String(length=40), nullable=True),
    sa.Column('collateral_status', sa.String(length=40), nullable=True),
    sa.Column('guarantor_status', sa.String(length=40), nullable=True),
    sa.Column('loan_reason', sa.String(length=255), nullable=True),
    sa.Column('supporting_documents', sa.String(length=40), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['loan_categoryID'], ['loan_category.id'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('ticketNo', sa.String(length=7), nullable=True),
    sa.Column('issue', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('collateral',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('collateralNo', sa.String(length=7), nullable=True),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['loanID'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guarantor',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('guarantorNo', sa.String(length=7), nullable=True),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['loanID'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('repayment',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('repaymentNo', sa.String(length=7), nullable=True),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('CheckoutRequestID', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['loanID'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ticket_message',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('ticketID', sa.String(length=8), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('sender', sa.String(length=50), nullable=True),
    sa.Column('staffID', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['staffID'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['ticketID'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_message')
    op.drop_table('repayment')
    op.drop_table('guarantor')
    op.drop_table('collateral')
    op.drop_table('ticket')
    op.drop_table('loan')
    op.drop_table('deposit')
    op.drop_table('member')
    op.drop_table('transaction')
    op.drop_table('staff')
    op.drop_table('loan_category')
    # ### end Alembic commands ###
