"""empty message

Revision ID: fe5d2cfa1536
Revises: 
Create Date: 2022-10-18 13:23:32.604199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5d2cfa1536'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('repayment',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('repaymentNo', sa.String(length=7), nullable=True),
    sa.Column('memberID', sa.String(length=8), nullable=False),
    sa.Column('loanID', sa.String(length=8), nullable=False),
    sa.Column('transactionID', sa.String(length=8), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('CheckoutRequestID', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['loanID'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['memberID'], ['member.id'], ),
    sa.ForeignKeyConstraint(['transactionID'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment')
    op.drop_table('guarantor')
    op.drop_table('collateral')
    op.drop_table('loan')
    op.drop_table('deposit')
    op.drop_table('member')
    op.drop_table('transaction')
    op.drop_table('staff')
    op.drop_table('loan_category')
    # ### end Alembic commands ###
